sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 2.2
python:
  - "3.6"
services: docker
script:
  - docker-compose build
before_deploy:
  echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin 
deploy:
  provider: script
  script:
    docker tag intellyseguradoraapi:latest tlribeiro/intellyseguradoraapi;
    docker push tlribeiro/intellyseguradoraapi;
  on:
    branch: master
after_success:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - pip3 uninstall wheel
  - pip3 install wheel
  - pip3 install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  - docker tag intellyseguradoraapi:latest $AWS_ECR_IMAGE_URL:latest
  - docker push $AWS_ECR_IMAGE_URL:latest
  - add-apt-repository ppa:eugenesan/ppa
  - apt-get update
  - apt-get install jq -v
  - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee /usr/bin/ecs-deploy
  - sudo chmod +x /usr/bin/ecs-deploy
  - echo "AWS ECS-Deploy está configurado!"
  - ecs-deploy -c $AWS_CLUSTER_NAME -n $AWS_SERVICE_NAME -i $AWS_ECR_IMAGE_URL:latest -r $AWS_DEFAULT_REGION -t 240

notifications:
  email: false