version: '3.4'
services:
  intellyseguradoraapi:
    image: ${DOCKER_REGISTRY-}intellyseguradoraapi
    build:
      context: .
      dockerfile: IntellySeguradoraApi/Dockerfile
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "80:80"
    networks:
      - tlr-networks
networks:
    tlr-networks:
        driver: bridge