version: '3.4'

services:
  db:
    image: docker-tlr-to-aws-mysql-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker_tlr_db
    ports:
      - "3308:3306"
    networks:
      - tlr-networks
  intellyseguradoraapi:
    image: ${DOCKER_REGISTRY-}intellyseguradoraapi
    build:
      context: .
      dockerfile: IntellySeguradoraApi/Dockerfile
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:80"
    links:
      - db
    depends_on:
      - db
    networks:
      - tlr-networks
networks:
    tlr-networks:
        driver: bridge