version: 0.2

phases:
  build:
    commands:
      - dotnet restore IntellySeguradoraApi/IntellySeguradoraApi.csproj
      - dotnet build IntellySeguradoraApi/IntellySeguradoraApi.csproj
      - dotnet publish IntellySeguradoraApi/IntellySeguradoraApi.csproj -o ./deploy/tlr-intelly-api
      - cp ./IntellySeguradoraApi/aws-windows-deployment-manifest.json ./IntellySeguradoraApi/deploy/.
artifacts:
  files:
    - '**/*'
  base-directory: 'IntellySeguradoraApi/deploy'